version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "./conf.d:/etc/nginx/conf.d"
    links:
      - node_express

  node_express:
    image: node:9.11.1-alpine
    container_name: node_express
    hostname: node_express
    volumes:
      - ".:/src"
    working_dir: /src
    command: [sh, -c, npm i && npm i typings -g && npm i -D typescript tslint ts-node nodemon shelljs @types/cookie-parser @types/morgan @types/shelljs --save && typings i debug express http-errors && npm i http-errors express cookie-parser morgan path --save && npm run-script build && npm start]
    ports:
      - "3000:3000"
#    links:
#      - mysql

#  mysql:
#    image: mysql:8.0.4-rc
#    container_name: mysql
#    hostname: mysql
#    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
#    ports:
#      - "3306:3306"
#    environment:
#      - "MYSQL_ROOT_PASSWORD=root"
#      - "MYSQL_DATABASE=todo"
