version: '3'

services:
  node_express:
    image: node:8.11.1-alpine
    container_name: node_express
    hostname: node_express
    volumes:
      - ".:/src"
    working_dir: /src
    command: > 
      sh -c
      "yarn global add typings
      && npm i
      && typings i
      && yarn build
      && yarn start"
    ports:
      - "3000:3000"
